# Generated by Django 4.2.8 on 2023-12-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Баланс'),
        ),
    ]
